language: python
install:
- pip install -r requirements.txt
script:
  - pip install -r requirements.txt
  - mkdocs build --config-file=docs/mkdocs/mkdocs.yml --verbose --clean
  - mv docs/mkdocs/site .
  - mkdir plottwist_repos
  - cd plottwist_repos
  - git clone https://github.com/PlotTwist-Short-Film/plottwist.git
  - cd ..
  - sphinx-apidoc -f -e -o docs/sphinx plottwist_repos/plottwist/plottwist --tocfile plottwist-modules
  - sphinx-build -M html ./docs/sphinx ./
  - cd html && touch .nojekyll && cd ../
  - cd site && touch .nojekyll && cd ../
  - mv site pipeline
  - mv pipeline html
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: html
    on:
      branch: master
