site_name: Plot Twist - Pipeline Docs
dev_addr: '127.0.0.1:9000'
sticky_navigation: False
nav:
  - Home: index.md
  - First Steps:
    - Setup Guide: setup.md
  - Artella App:
    - What's Artella App?: pipeline/artella/app.md
    - Installing Artella App: pipeline/artella/installing.md
    - Managing the Artella App: pipeline/artella/managing.md
  - Plot Twist Launcher:
    - What's Plot Twist Launcher?: pipeline/launcher/app.md
    - Installing Plot Twist Launcher: pipeline/launcher/installation.md
    - Using Plot Twist Launcher: pipeline/launcher/usage.md
    - Uninstalling Plot Twist Launcher: pipeline/launcher/uninstall.md
  - Plot Twist Pipeline:
    - Software:
        - Versions: pipeline/software/versions.md
        - Installation:
            - Python: pipeline/software/installingpython.md
            - Maya: pipeline/software/installingmaya.md
            - Arnold: pipeline/software/installingarnold.md
    - Tools:
      - Welcome: pipeline/tools/welcome.md
      - Tray: pipeline/tools/tray.md
      - Shelf: pipeline/tools/shelf.md
      - Changelog: pipeline/tools/changelog.md
      - Assets Manager: pipeline/tools/assetsmanager.md
      - Artella Manager: pipeline/tools/artellamanager.md
      - Artella Uploader: pipeline/tools/artellauploader.md
    - Assets:
        - Props: pipeline/assets/props.md
    - Departments:
        - Modeling:
            - Set Dressing - Model Guide: pipeline/departments/modeling/dressingassetsmodelguide.md
    - FAQ:
      - How to set Plot Twist Project?: pipeline/faq/setproject.md
      - How to save a file?: pipeline/faq/savefile.md
      - How to lock/unlock a file?: pipeline/faq/lockunlockfile.md
      - How to upload a new file version?: pipeline/faq/newversion.md
  - Plot Twist Development:
      - Development Setup: pipeline/dev/setup.md
      - ArtellaPipe: pipeline/dev/artellapipe.md
      - How to create new tools: pipeline/dev/tools.md
      - How to deploy new versions of the pipeline: pipeline/dev/deploy.md
      - How to add new documentation: pipeline/dev/documentation.md
theme:
  name: 'material'
  logo: 'img/plottwist.png'
  feature:
    tabs: true
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.tasklist
plugins:
  - markdownextradata: {}
extra:
  project:
    name: "Plot Twist"
    exe: "plottwist_launcher.exe"
extra_css:
  - 'stylesheets/plottwist.css'